apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-server
spec:
  hosts:
  - server-1 # interpreted as server-1.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: server-2 # interpreted as server-2.default.svc.cluster.local
