apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-httpbin
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
